### PR TITLE
Filter out sensitive data from the HTTP headers

### PR DESCRIPTION
**Pull request by raphaelcruzeiro**
The HTTP headers were not being stripped of sensitive data as the request data was. This PR fixes that.

### CODE REVIEW

**Comment by raphaelcruzeiro** [comment]
Not really sure if this project accepts external contributions but since this bugsnag integration plays such an important part on [Tangerine](https://tangerine.app), I decided to share here this very small fix I made so that we wouldn't leak our user's authentication tokens on our logs ;)

**Comment by siemensikkema** [comment]
@raphaelcruzeiro Thanks for you PR! We are always open for contributions 🙂 Your PR fixes an important bug so thanks for that! I'd like to avoid the force unwrap you're using, though. Can you find a way to avoid that? Also consider https://developer.apple.com/documentation/swift/array/3126956-reduce for a possibly more compact way to create the header dict. If you don't get to it, I'll try to see to it when I get some time but that might be a while.

**Comment by raphaelcruzeiro** [comment]
@siemensikkema No worries! I've changed the code to avoid that force cast and replaced the reduce with `reduce(into:)` (thanks for this tip btw. I didn't know this variant of reduce and it's a way nicer way to deal with reducing stuff into a dictionary).

**Review by siemensikkema — APPROVED** [review]
Looks really good! Thanks for the quick finishing touches

**Comment by raphaelcruzeiro** [comment]
Glad to help ;)

**Pull request merged**
